---
- name: Clone Single Repository
  include_tasks: addkey.yml
  when:
    - repo is defined
    - git_repos is undefined

- name: clone all Repositories
  include_tasks: single.yml
  loop: "{{ git_repos if git_repos is defined else [] }}"
  when:
    - git_repos is defined
  vars:
    repo: "{{ git_repo_item.repo }}"
    dest: "{{ git_repo_item.dest }}"
  loop_control:
    loop_var: git_repo_item
