---
- name: Clone Single Repository
  include_tasks: single.yml
  when:
    - repo is defined
    - git_repos is undefined

- name: clone all Repositories
  include_tasks: single.yml
  loop: "{{ git_repos if git_repos is defined else [] }}"
  when:
    - git_repos is defined
  vars:
    repo: "{{ git_repo_item.repo }}"
    dest: "{{ git_repo_item.dest }}"
    version: "{{ git_repo_item.version if git_repo_item.version is defined else omit }}"
    force: "{{ git_repo_item.force if (git_repo_item.force is defined and git_repo_item.force == 'yes') else 'no' }}"
  loop_control:
    loop_var: git_repo_item