---
- name: "Clone Repository {{ repo }}"
  git:
    repo: "{{ repo }}"
    dest: "{{ dest }}"
    version: "{{ version if version is defined else 'master' }}"
    force: "{{ 'yes' if ((force is defined and force == 'yes') or (rewrite is defined and rewrite == 'yes')) else 'no' }}"